# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      maven-dependencies:
        patterns:
          - "*maven*"
      spring-dependencies:
        patterns:
          - "*org.springframework*"
      apache-dependencies:
        patterns:
          - "*org.apache*"
          - "commons-io*"
      other-dependencies:
        patterns:
          - "*" 
    commit-message:
      prefix: "build:"
    open-pull-requests-limit: 5
