name: build-and-run-test
description: build the application and run test

inputs:
  postgres-db:
    description: "Postgres database name"
    required: true
  postgres-user:
    description: "Postgres username"
    required: true
  postgres-password:
    description: "Postgres password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Set up PostgreSQL
      uses: docker://postgres:latest
      env:
        POSTGRES_DB: ${{ inputs.postgres-db }}
        POSTGRES_USER: ${{ inputs.postgres-user }}
        POSTGRES_PASSWORD: ${{ inputs.postgres-password }}
    - name: Wait for PostgreSQL to start
      run: |
        while ! pg_isready -q -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL to start..."
          sleep 1
        done
      shell: bash
    - name: Maven Build
      id: maven-build
      run: |
        mvn -U -B clean install
      shell: bash
